#!/usr/bin/env bash
set -euo pipefail
thr="$1"; cov="$2"; unreachable="$3"; oversized="$4"; sizeExceeded="$5"; totalSizeMB="$6"; totalAnchors="$7"; reachable="$8"
FACTORS=()
[ "$cov" -lt "$thr" ] && FACTORS+=("Coverage below threshold (${cov}% < ${thr}%)")
[ "$unreachable" -gt 0 ] && FACTORS+=("${unreachable} unreachable anchors")
[ "$oversized" -gt 0 ] && FACTORS+=("${oversized} oversized anchors")
[ "$sizeExceeded" = true ] && FACTORS+=("Aggregate size exceeded (${totalSizeMB}MB)")
{
  echo "### dream"; echo "SPECTRA"; echo; echo "### archetype"; echo "Operations"; echo; echo "### domain"; echo "governance"; echo; echo "### initiativeTitle"; echo "contextAnchorCoverageGapResolution"; echo; echo "### purpose"; echo "Resolve reachability and size compliance gaps for context anchors to restore reliable contextual intelligence services."; echo; echo "### currentFindings"; for f in "${FACTORS[@]}"; do echo "- $f"; done; echo; echo "### metrics"; echo "- Total anchors: $totalAnchors"; echo "- Reachable: $reachable"; echo "- Coverage: ${cov}% (threshold ${thr}%)"; echo "- Unreachable: $unreachable"; echo "- Oversized: $oversized"; echo "- Total size: ${totalSizeMB}MB"; echo; echo "Auto-generated by check-anchor-health.";
} > /tmp/issue_body.md
