name: capture-runtime-metrics

# Spectrafy-Contract:
#   responsibility: Collect recent workflow run durations & append snapshot to architecture doc
#   inputs:
#     - schedule/dispatch (triggers)
#   outputs:
#     - runtime_metrics.md (raw table)
#     - runtime_metrics.json (JSON summary)
#   metrics:
#     - workflow_median_runtime: per-workflow median seconds (table)
#     - workflow_p90_runtime: per-workflow p90 seconds (table)
#   idempotent: true
#   autonomous: true
#   ownership: governance
#   replacementPolicy: immediate-remove-legacy

on:
  schedule:
    - cron: '17 2 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  runtimes:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: setup-python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: run-collector
        id: collect
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_REPOSITORY: SPECTRADataSolutions/framework
        run: |
          python framework/scripts/governance/collect_workflow_run_metrics.py > runtime_metrics.md
          echo "---" >> runtime_metrics.md
          grep JSON_SUMMARY runtime_metrics.md | sed 's/JSON_SUMMARY=//' > runtime_metrics.json || true
          echo "json=$(cat runtime_metrics.json | tr '\n' ' ' | sed 's/`/\`/g')" >> $GITHUB_OUTPUT
      - name: append-architecture-doc
        run: |
          ARCH=framework/docs/governance/workflow_consolidation_architecture.md
          echo "\n### Runtime Metrics Snapshot ($(date -u +%Y-%m-%dT%H:%MZ))\n" >> $ARCH
          sed -n '1,120p' runtime_metrics.md >> $ARCH
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add $ARCH runtime_metrics.* || true
          if ! git diff --cached --quiet; then
            git commit -m "chore(metrics): append runtime workflow metrics snapshot" || true
            git push || true
          fi
      - name: upload-artifacts
        uses: actions/upload-artifact@v4
        with:
          name: runtime-metrics
          path: |
            runtime_metrics.md
            runtime_metrics.json
          retention-days: 14
