name: guard-no-tabs

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'
  push:
    branches: [ main ]
    paths:
      - '.github/workflows/*.yml'

permissions:
  contents: read

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Fail if tab characters present in workflows
        run: |
          if grep -P "\t" -n .github/workflows/*.yml; then
            echo '::error title=Tab characters found::Remove all tab characters from workflow YAML.'
            exit 1
          fi
          echo "No tabs detected."
