name: policy-attestation

on:
  workflow_dispatch: {}
  schedule:
    - cron: "11 3 * * *"

permissions:
  contents: write # needed only here to commit updated digests

jobs:
  attest:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: compute-digests
        id: digests
        shell: bash
        run: |
          set -euo pipefail
          echo "Computing policy digests" >&2
          out_file=framework/policy-digests.txt
          echo "# Canonical policy file digests (SHA256)" > "$out_file"
          echo "# Regenerated: $(date -u +%Y-%m-%dT%H:%M:%SZ)" >> "$out_file"
          echo >> "$out_file"
          for f in framework/policies/*policy.*; do
            [ -f "$f" ] || continue
            sha=$(sha256sum "$f" | awk '{print $1}')
            printf "%s  %s\n" "$sha" "${f#framework/}" >> "$out_file"
          done
          sort -o "$out_file" "$out_file"
          echo 'file<<EOF' >> $GITHUB_OUTPUT
          cat "$out_file" >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT
      - name: detect-change
        id: change
        shell: bash
        run: |
          set -euo pipefail
          if git diff --quiet -- framework/policy-digests.txt 2>/dev/null; then
            echo "changed=false" >> $GITHUB_OUTPUT || true
          else
            echo "changed=true" >> $GITHUB_OUTPUT
          fi || echo "changed=true" >> $GITHUB_OUTPUT
      - name: commit-updated-digests
        if: steps.change.outputs.changed == 'true'
        run: |
          git config user.name 'policy-attestor'
          git config user.email 'policy-attestor@users.noreply.github.com'
          git add framework/policy-digests.txt
          git commit -m 'chore(attestation): update policy digests'
          git push
      - name: summarize
        uses: actions/github-script@v7
        with:
          script: |
            const changed = core.getInput('changed') === 'true';
            core.summary.addHeading('Policy Attestation').addRaw(changed? 'Digests updated.' : 'No digest changes.').write();
