name: "🔗 Dependency"
description: Register a dependency between two elements for traceability and impact checks.
title: "🔗 [Dependency] <from> → <to>"
labels: ["type:dependency","status:registered"]
body:
  - type: dropdown
    id: pillar
    attributes:
      label: pillar
      options: [Protection, Sustenance, Innovation, Operations, Engagement, Growth, Guidance]
    validations: { required: true }

  - type: input
    id: domain
    attributes:
      label: domain
      placeholder: "dataPlatform"
    validations: { required: true }

  - type: input
    id: fromElement
    attributes:
      label: fromElement
      description: id or url of the upstream element (repo, service, initiative, epic)
    validations: { required: true }

  - type: input
    id: toElement
    attributes:
      label: toElement
      description: id or url of the downstream element (repo, service, initiative, epic)
    validations: { required: true }

  - type: textarea
    id: rationale
    attributes:
      label: rationale
      description: why this dependency exists and how it is used

  - type: checkboxes
    id: automationOptions
    attributes:
      label: automationOptions
      options:
        - label: updateDependencyGraph
        - label: triggerRippleImpactChecks
