name: New Epic
description: Multi-week deliverable aligned to governance; generates stories and tasks.
title: "🗂️ [Epic] <shortTitle>"
labels: ["type:epic","status:planning"]
body:
  - type: dropdown
    id: pillar
    attributes:
      label: pillar
      options: [governance, product, engineering, operations, marketing, sales]
    validations: { required: true }

  - type: input
    id: domain
    attributes:
      label: domain
      placeholder: "experienceEngineering"
    validations: { required: true }

  - type: input
    id: initiativeId
    attributes:
      label: initiativeId
      description: link to parent initiative if applicable

  - type: textarea
    id: goal
    attributes:
      label: goal
      description: short goal statement
    validations: { required: true }

  - type: textarea
    id: acceptanceCriteria
    attributes:
      label: acceptanceCriteria
      description: testable outcomes (one per line)
      placeholder: |
        - supportsGestureAndVoice
        - rendersAt60fpsInPrototype
        - passesAccessibilityAA
    validations: { required: true }

  - type: textarea
    id: dependencies
    attributes:
      label: dependencies
      description: repos/systems/other epics

  - type: checkboxes
    id: automationOptions
    attributes:
      label: automationOptions
      options:
        - label: generateStoriesAndTasks
        - label: runImpactAnalysis
        - label: computeExecutionReadinessScore
