name: "🧪 Experiment"
description: Capture research or discovery work to test a hypothesis.
title: "🧪 [Experiment] <shortTitle>"
labels: ["type:experiment","status:proposed"]
body:
  - type: dropdown
    id: archetype
    attributes:
      label: archetype
      options: [Guidance, Innovation, Engagement, Operations, Protection, Sustenance, Growth]
    validations: { required: true }

  - type: input
    id: domain
    attributes:
      label: domain
      placeholder: "aiResearch"

  - type: textarea
    id: hypothesis
    attributes:
      label: hypothesis
      description: what do you believe will happen?
    validations: { required: true }

  - type: textarea
    id: method
    attributes:
      label: method
      description: how will you test it?
    validations: { required: true }

  - type: textarea
    id: successCriteria
    attributes:
      label: successCriteria
      description: measurable pass/fail criteria
    validations: { required: true }

  - type: checkboxes
    id: automationOptions
    attributes:
      label: automationOptions
      options:
        - label: createStoriesFromSuccessCriteria
        - label: archiveResultsToKnowledgeBase
