name: "🚨 Incident"
description: Record and manage a specific event or disruption.
title: "🚨 [Incident] <shortTitle>"
labels: ["type:incident","status:ready"]
body:
  - type: textarea
    id: symptoms
    attributes:
      label: symptoms
      description: what was observed that indicated the incident
    validations: { required: true }

  - type: textarea
    id: diagnosis
    attributes:
      label: diagnosis
      description: summary of findings or suspected root cause

  - type: textarea
    id: resolution
    attributes:
      label: resolution
      description: step-by-step actions taken to resolve the incident
      placeholder: "1. step one\n2. step two"
    validations: { required: true }
