name: "🚨 Incident"
description: Record and triage a production or operational incident.
title: "🚨 [Incident] <shortTitle>"
labels: ["type:incident","status:triage"]
body:
  - type: textarea
    id: summary
    attributes:
      label: summary
    validations: { required: true }
  - type: textarea
    id: impact
    attributes:
      label: impact
    validations: { required: true }
  - type: textarea
    id: timeline
    attributes:
      label: timeline
  - type: textarea
    id: mitigation
    attributes:
      label: mitigation
  - type: textarea
    id: rootCause
    attributes:
      label: rootCause
  - type: checkboxes
    id: automationOptions
    attributes:
      label: automationOptions
      options:
        - label: createFollowUpTasks
        - label: notifyStakeholders
