name: "🚀 Initiative"
description: Strategic or operational work starting point. Auto-generates projects, epics, stories, tasks, work packages, and sprint plans.
title: "🚀 [Initiative] <shortTitle>"
type: "initiative"
assignees: ["copilot"]
projects: ["SPECTRA"]
labels: ["type:initiative","status:planning"]

body:
  - type: markdown
    attributes:
      value: |
        ## SPECTRA Standards
        - British English spelling
        - SPECTRA in ALL CAPS
        - Repo names: camelCase, singular nouns
        - camelCase only for Fabric pipelines, repo names, and code
        - No secrets in code
        **Dream:** SPECTRA
        ☁️ theDream — All cross-pillar, meta, or org-wide work is governed by theDream. Never categorise or label it as a pillar or archetype.

  - type: markdown
    attributes:
      value: |
        ### developmentMethodology options
        - Behaviour-Driven Development (BDD) – user-facing features & behaviour scenarios
        - Test-Driven Development (TDD) – technical components & reliability
        - Domain-Driven Design (DDD) – complex business logic & domain modelling
        - Data-Driven Development – metrics & usage-driven work
        - Feature-Driven Development (FDD) – incremental feature delivery
        - Hybrid/Other – specify in notes

  - type: dropdown
    id: pillar
    attributes:
      label: pillar
      description: High-level capability categorisation (Dream → Pillar → Domain → Repo)
      options: [Protection, Sustenance, Innovation, Operations, Engagement, Growth, Guidance]
    validations:
      required: true

  - type: input
    id: domain
    attributes:
      label: domain
      description: Single-token camelCase (singular concept) pertinent to pillar
      placeholder: "governance"
    validations:
      required: true

  - type: input
    id: initiativeTitle
    attributes:
      label: initiativeTitle
      description: Short, clear name
      placeholder: "spectraWebsiteV1"
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: purpose
      description: One sentence explaining why this initiative exists and the outcome it aims to achieve
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: scope
    validations:
      required: true

  - type: textarea
    id: capabilityAreas
    attributes:
      label: capabilityAreas
      description: One per line; becomes epics 1:1
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: deliverables
    validations:
      required: true

  - type: textarea
    id: successIndicators
    attributes:
      label: successIndicators
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: constraints
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: dependencies

  - type: dropdown
    id: developmentMethodology
    attributes:
      label: developmentMethodology
      options:
        - Behaviour-Driven Development (BDD) – user-facing features & behaviour scenarios
        - Test-Driven Development (TDD) – technical components & reliability
        - Domain-Driven Design (DDD) – complex business logic & domain modelling
        - Data-Driven Development – metrics & usage-driven work
        - Feature-Driven Development (FDD) – incremental feature delivery
        - Hybrid/Other – specify in notes
    validations:
      required: true

  - type: textarea
    id: nonNegotiables
    attributes:
      label: nonNegotiables
    validations:
      required: true

  - type: textarea
    id: reusePriority
    attributes:
      label: reusePriority

  - type: textarea
    id: securityPosture
    attributes:
      label: securityPosture

  - type: textarea
    id: humanInTheLoop
    attributes:
      label: humanInTheLoop

  - type: textarea
    id: testStrategy
    attributes:
      label: testStrategy

  - type: textarea
    id: rolloutPlan
    attributes:
      label: rolloutPlan

  - type: textarea
    id: lessonsFromPastInitiatives
    attributes:
      label: lessonsFromPastInitiatives

  - type: checkboxes
    id: automationOptions
    attributes:
      label: automationOptions
      options:
        - label: generateInitiativeIdAndUuid
        - label: generateProjectsEpicsStories
        - label: generateWorkPackagesAndSprintPlan
        - label: runImpactAnalysis
        - label: runFutureConsequenceSimulation
        - label: computeExecutionReadinessScore
        - label: generateMaturityForecastTimeline

  - type: dropdown
    id: outcomeStatus
    attributes:
      label: outcomeStatus
      options: [planned, inProgress, delivered, delayed, cancelled]

  - type: textarea
    id: postmortem
    attributes:
      label: postmortem
      description: Link to retro or brief notes (root cause, mitigations)
