name: "🚀 Initiative"
description: Strategic or operational work starting point. Auto-generates projects, epics, stories, tasks, work packages, and sprint plans.
title: "🚀 [Initiative] <shortTitle>"
type: "initiative"
assignees: ["github-copilot"]
projects: ["SPECTRA"]
labels: []  # Reserved only for truly orthogonal tags not captured elsewhere

body:
  - type: markdown
    attributes:
      value: |
        ## SPECTRA Standards
        - British English spelling
        - SPECTRA in ALL CAPS
        - camelCase only for Fabric pipelines, repo names, and code
        - No secrets in code

  - type: dropdown
    id: dream
    attributes:
      label: dream
      description: Organisational vision and aspiration
      options: [SPECTRA]
      default: 0
    validations: { required: true }

  - type: dropdown
    id: archetype
    attributes:
      label: archetype
      description: High-level capability categorisation (Dream → Archetype → Domain → Repo)
      options: [Guidance, Innovation, Engagement, Operations, Protection, Sustenance, Growth]
    validations: { required: true }

  - type: input
    id: domain
    attributes:
      label: domain
      description: Single-word camelCase domain pertinent to archetype
      placeholder: "webPlatform"
    validations: { required: true }

  - type: input
    id: initiativeTitle
    attributes:
      label: initiativeTitle
      description: Short, clear name
      placeholder: "spectraWebsiteV1"
    validations: { required: true }

  - type: textarea
    id: purpose
    attributes:
      label: purpose
      description: One sentence explaining why this initiative exists and the outcome it aims to achieve
    validations: { required: true }

  - type: textarea
    id: scope
    attributes:
      label: scope
      description: Define inScope and outOfScope
      placeholder: |
        inScope: ...
        outOfScope: ...
    validations: { required: true }

  - type: textarea
    id: capabilityAreas
    attributes:
      label: capabilityAreas
      description: One per line; becomes epics 1:1
      placeholder: |
        immersiveVisionDefinition
        dynamicStructureGeneration
        interactiveEditing
    validations: { required: true }

  - type: textarea
    id: deliverables
    attributes:
      label: deliverables
      description: Bullet list of concrete outputs expected from this initiative
      placeholder: |
        - vrOnboardingFlow
        - liveRoadmap
        - deltaMemoryStore
    validations: { required: true }

  - type: textarea
    id: successIndicators
    attributes:
      label: successIndicators
      description: Measurable outcomes
      placeholder: |
        - blueprintCreatedIn<=30min
        - instantVisualUpdates
        - zeroManualBacklogEdits
    validations: { required: true }

  - type: textarea
    id: constraints
    attributes:
      label: constraints
      description: Tech/budget/resource rules
      placeholder: |
        - fabricFirst
        - BritishEnglishSpelling
        - SPECTRA in all caps
        - camelCase only in Fabric pipelines, repo names, and code
        - noSecretsInCode
    validations: { required: true }

  - type: textarea
    id: dependencies
    attributes:
      label: dependencies
      description: Related initiatives, repos, systems

  - type: dropdown
    id: developmentMethodology
    attributes:
      label: developmentMethodology
      description: Choose the most appropriate 'Driven Development' approach
      options:
        - Behaviour-Driven Development (BDD) – user-facing features & behaviour scenarios
        - Test-Driven Development (TDD) – technical components & reliability
        - Domain-Driven Design (DDD) – complex business logic & domain modelling
        - Data-Driven Development – metrics & usage-driven work
        - Feature-Driven Development (FDD) – incremental feature delivery
        - Hybrid/Other – specify in notes
    validations: { required: true }

  - type: textarea
    id: nonNegotiables
    attributes:
      label: nonNegotiables
      placeholder: |
        - BritishEnglishSpelling
        - SPECTRA in all caps
        - camelCase only for Fabric pipelines, repo names, and code
        - noSecretsInCode
    validations: { required: true }

  - type: textarea
    id: reusePriority
    attributes:
      label: reusePriority
      placeholder: |
        prefer: ["spectra/ui","spectra/utils","ms-fabric"]
        avoid: ["customAuth","one-off visuals"]

  - type: dropdown
    id: buildVsBuyBias
    attributes:
      label: buildVsBuyBias
      options: [reuse, buy, build]
      description: Default stance for this initiative

  - type: textarea
    id: securityPosture
    attributes:
      label: securityPosture
      placeholder: |
        dataClass: confidential
        auth: EntraID
        secrets: KeyVault refs only

  - type: textarea
    id: compliance
    attributes:
      label: compliance
      placeholder: |
        - gdpr: required
        - retention: 365d
        - iso27001: controls A.12,A.14

  - type: dropdown
    id: accessibility
    attributes:
      label: accessibility
      options: ["WCAG 2.2 A","WCAG 2.2 AA","WCAG 2.2 AAA"]
      default: 1

  - type: textarea
    id: performanceSLOs
    attributes:
      label: performanceSLOs
      placeholder: |
        p95Latency<=200ms
        dashboardLoad<=3s
        monthlyCloudCost<=£X

  - type: textarea
    id: observability
    attributes:
      label: observability
      placeholder: |
        metrics: required
        traces: required
        logs: structured+PII-safe

  - type: textarea
    id: aiUsagePolicy
    attributes:
      label: aiUsagePolicy
      placeholder: |
        allowed: planning, scaffolding, tests
        disallowed: secrets, prod data
        modelTier: GPT-5-pro or better

  - type: textarea
    id: humanInTheLoop
    attributes:
      label: humanInTheLoop
      placeholder: |
        checkpoints:
          - architecture: [role/title]
          - security: [role/title]

  - type: textarea
    id: testStrategy
    attributes:
      label: testStrategy
      placeholder: |
        mix: BDD(user) + TDD(core)
        coverage>=80%
        criticalPaths: listed

  - type: textarea
    id: i18n
    attributes:
      label: i18n
      value: |
        locales: ["en-GB"]
        formats: UK

  - type: textarea
    id: rolloutPlan
    attributes:
      label: rolloutPlan
      placeholder: |
        featureFlags: required
        canary: 5%→25%→100%
        rollback: one-click

  - type: textarea
    id: sustainability
    attributes:
      label: sustainability
      placeholder: |
        carbonBudget: low
        hardwarePref: efficient/GPU-pool

  - type: textarea
    id: definitionOfDone
    attributes:
      label: definitionOfDone
      placeholder: |
        - docs updated
        - tests passing & coverage met
        - dashboards wired
        - runbook + oncall note

  - type: textarea
    id: lessonsFromPastInitiatives
    attributes:
      label: lessonsFromPastInitiatives
      description: Auto-filled summary of risks/mitigations from similar initiatives
      placeholder: "(auto-populated by analyse-initiatives workflow)"

  - type: checkboxes
    id: automationOptions
    attributes:
      label: automationOptions
      description: Choose what runs on submit
      options:
        - label: generateInitiativeIdAndUuid
        - label: generateProjectsEpicsStories
        - label: generateWorkPackagesAndSprintPlan
        - label: runImpactAnalysis
        - label: runFutureConsequenceSimulation
        - label: computeExecutionReadinessScore
        - label: generateMaturityForecastTimeline

  - type: dropdown
    id: outcomeStatus
    attributes:
      label: outcomeStatus
      options: [planned, inProgress, delivered, delayed, cancelled]

  - type: textarea
    id: postmortem
    attributes:
      label: postmortem
      description: Link to retro or brief notes (root cause, mitigations)
      placeholder: |
        rootCause: ...
        mitigations: ...
        links: [...]
