name: "🚀 Initiative"
description: Strategic or operational work starting point. Auto-generates projects, epics, stories, tasks, work packages, and sprint plans.
title: "🚀 [Initiative] <shortTitle>"
type: "initiative"
assignees: ["github-copilot"]
projects: ["SPECTRA"]
labels: []

body:
  - type: markdown
    attributes:
      value: |
        ## SPECTRA Standards
        - British English spelling
        - SPECTRA in ALL CAPS
        - Repo names: camelCase, singular nouns
        - camelCase only for Fabric pipelines, repo names, and code
        - No secrets in code
        **Dream:** SPECTRA

  - type: dropdown
    id: pillar
    attributes:
      label: pillar
      description: High-level capability categorisation (Dream → Pillar → Domain → Repo)
      options: [Guidance, Innovation, Engagement, Operations, Protection, Sustenance, Growth]
    validations:
      required: true

  - type: input
    id: domain
    attributes:
      label: domain
      description: Single-token camelCase (singular concept) pertinent to archetype
      placeholder: "governance"
    validations:
      required: true

  - type: input
    id: initiativeTitle
    attributes:
      label: initiativeTitle
      description: Short, clear name
      placeholder: "spectraWebsiteV1"
    validations:
      required: true

  - type: textarea
    id: purpose
    attributes:
      label: purpose
      description: One sentence explaining why this initiative exists and the outcome it aims to achieve
    validations:
      required: true

  - type: textarea
    id: scope
    attributes:
      label: scope
      description: Define inScope and outOfScope
      placeholder: |
        inScope: ...
        outOfScope: ...
    validations:
      required: true

  - type: textarea
    id: capabilityAreas
    attributes:
      label: capabilityAreas
      description: One per line; becomes epics 1:1
      placeholder: |
        immersiveVisionDefinition
        dynamicStructureGeneration
        interactiveEditing
    validations:
      required: true

  - type: textarea
    id: deliverables
    attributes:
      label: deliverables
      description: Bullet list of concrete outputs expected from this initiative
      placeholder: |
        - vrOnboardingFlow
        - liveRoadmap
        - deltaMemoryStore
    validations:
      required: true

  - type: textarea
    id: successIndicators
    attributes:
      label: successIndicators
      description: Measurable outcomes
      placeholder: |
        - blueprintCreatedIn<=30min
        - instantVisualUpdates
        - zeroManualBacklogEdits
    validations:
      required: true

  - type: textarea
    id: constraints
    attributes:
      label: constraints
      description: Tech/budget/resource rules
      placeholder: |
        - fabricFirst
        - BritishEnglishSpelling
        - SPECTRA in ALL CAPS
        - camelCase only in Fabric pipelines, repo names, and code
        - noSecretsInCode
    validations:
      required: true

  - type: textarea
    id: dependencies
    attributes:
      label: dependencies
      description: Related initiatives, repos, systems

  - type: dropdown
    id: developmentMethodology
    attributes:
      label: developmentMethodology
      description: Choose the most appropriate 'Driven Development' approach
      options:
        - Behaviour-Driven Development (BDD) – user-facing features & behaviour scenarios
        - Test-Driven Development (TDD) – technical components & reliability
        - Domain-Driven Design (DDD) – complex business logic & domain modelling
        - Data-Driven Development – metrics & usage-driven work
        - Feature-Driven Development (FDD) – incremental feature delivery
        - Hybrid/Other – specify in notes
    validations:
      required: true

  - type: textarea
    id: nonNegotiables
    attributes:
      label: nonNegotiables
      placeholder: |
        - BritishEnglishSpelling
        - SPECTRA in ALL CAPS
        - camelCase only for Fabric pipelines, repo names, and code
        - noSecretsInCode
    validations:
      required: true

  - type: textarea
    id: reusePriority
    attributes:
      label: reusePriority
      placeholder: |
        prefer: ["spectra/ui","spectra/utils","ms-fabric"]
        avoid: ["customAuth","one-off visuals"]

  - type: textarea
    id: securityPosture
    attributes:
      label: securityPosture
      placeholder: |
        dataClass: confidential
        auth: EntraID
        secrets: KeyVault refs only

  - type: textarea
    id: humanInTheLoop
    attributes:
      label: humanInTheLoop
      placeholder: |
        checkpoints:
          - architecture: [role/title]
          - security: [role/title]

  - type: textarea
    id: testStrategy
    attributes:
      label: testStrategy
      placeholder: |
        mix: BDD(user) + TDD(core)
        coverage>=80%
        criticalPaths: listed

  - type: textarea
    id: rolloutPlan
    attributes:
      label: rolloutPlan
      placeholder: |
        featureFlags: required
        canary: 5%→25%→100%
        rollback: one-click

  - type: textarea
    id: lessonsFromPastInitiatives
    attributes:
      label: lessonsFromPastInitiatives
      description: Auto-filled summary of risks/mitigations from similar initiatives
      placeholder: "(auto-populated by analyse-initiatives workflow)"

  - type: checkboxes
    id: automationOptions
    attributes:
      label: automationOptions
      description: Choose what runs on submit
      options:
        - label: generateInitiativeIdAndUuid
        - label: generateProjectsEpicsStories
        - label: generateWorkPackagesAndSprintPlan
        - label: runImpactAnalysis
        - label: runFutureConsequenceSimulation
        - label: computeExecutionReadinessScore
        - label: generateMaturityForecastTimeline

  - type: dropdown
    id: outcomeStatus
    attributes:
      label: outcomeStatus
      options: [planned, inProgress, delivered, delayed, cancelled]

  - type: textarea
    id: postmortem
    attributes:
      label: postmortem
      description: Link to retro or brief notes (root cause, mitigations)
      placeholder: |
        rootCause: ...
        mitigations: ...
        links: [...]
