name: "📜 Procedure"
description: Document a repeatable operational or technical process.
title: "📜 [Procedure] <shortTitle>"
labels: ["type:procedure","status:ready"]
body:
  - type: textarea
    id: overview
    attributes:
      label: overview
      description: summary of the procedure’s purpose
    validations: { required: true }

  - type: textarea
    id: steps
    attributes:
      label: steps
      description: step-by-step instructions
      placeholder: "1. step one\n2. step two"
    validations: { required: true }

  - type: textarea
    id: triggers
    attributes:
      label: triggers
      description: alerts, conditions, or events that require using this procedure
      placeholder: "- triggerName: action"
