name: "📖 Story"
description: End-user facing deliverable in one sprint.
title: "📖 [Story] <shortTitle>"
labels: ["type:story","status:todo"]
body:
  - type: dropdown
    id: pillar
    attributes:
      label: pillar
      options: [governance, product, engineering, operations, marketing, sales]
    validations: { required: true }

  - type: input
    id: domain
    attributes:
      label: domain
      placeholder: "experienceEngineering"
    validations: { required: true }

  - type: input
    id: parentEpic
    attributes:
      label: parentEpic
      description: link or id

  - type: textarea
    id: description
    attributes:
      label: description
    validations: { required: true }

  - type: textarea
    id: acceptanceCriteria
    attributes:
      label: acceptanceCriteria
      description: testable outcomes (one per line)
      placeholder: |
        - condition one
        - condition two
    validations: { required: true }

  - type: input
    id: effortEstimate
    attributes:
      label: effortEstimate
      placeholder: "3d"
