name: "🛡️ Vulnerability"
description: Report a vulnerability for private triage.
title: "🛡️ [Vulnerability] <shortTitle>"
labels: ["type:vulnerability","status:private"]
body:
  - type: dropdown
    id: pillar
    attributes:
      label: pillar
      options: [governance, product, engineering, operations, marketing, sales]
    validations: { required: true }

  - type: input
    id: domain
    attributes:
      label: domain
      placeholder: "platformSecurity"
    validations: { required: true }

  - type: textarea
    id: summary
    attributes:
      label: summary
      description: brief description — do not include secrets
    validations: { required: true }

  - type: textarea
    id: severity
    attributes:
      label: severity
      description: choose from low, medium, high, critical
    validations: { required: true }

  - type: textarea
    id: impact
    attributes:
      label: impact
      description: systems, data, or processes affected
    validations: { required: true }

  - type: textarea
    id: reproduction
    attributes:
      label: reproduction
      description: minimal steps to reproduce if safe to share

  - type: textarea
    id: mitigation
    attributes:
      label: mitigation
      description: any suggested temporary or permanent fixes

  - type: checkboxes
    id: automationOptions
    attributes:
      label: automationOptions
      options:
        - label: restrictVisibilityToSecurityTeam
        - label: createImmediateMitigationTask
        - label: startImpactAnalysis
