name: removed-check-anchor-health
on:
  workflow_dispatch: {}

jobs:
  removed:
    runs-on: ubuntu-latest
    steps:
      - run: echo "check-anchor-health workflow has been deprecated and removed. No action performed."
