name: enforce-chief-of-staff

on:
  workflow_dispatch:
  push:
    paths:
      - "agents/registry/employmentLogIndex.json"
      - "organisation/contracts/chiefOfStaff.json"
      - "organisation/scripts/enforceChiefOfStaff.py"
      - "people/**"
  pull_request:
    paths:
      - "people/registry/employmentLogIndex.json"
      - "organisation/contracts/chiefOfStaff.json"
      - "organisation/scripts/enforceChiefOfStaff.py"
      - "people/**"

jobs:
  enforceChiefOfStaff:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout triggering repo
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository }}
          ref: ${{ github.ref }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run Chief of Staff Enforcement
        run: |
          if [ -f organisation/scripts/enforceChiefOfStaff.py ]; then
            python organisation/scripts/enforceChiefOfStaff.py
          else
            echo "❌ Script not found in target repo!"
            exit 1
          fi
