name: deprecated-create-repository-instance

on:
  workflow_dispatch:
    inputs:
      repoName:
        description: "service (camelCase) — will become repository name"
        required: true
        type: string
      pillar:
        description: "Guidance|Innovation|Engagement|Execution|Protection|Sustenance|Growth"
        required: true
        type: string
      domain:
        description: "single-token camelCase (e.g. platformSecurity)"
        required: true
        type: string
      capability:
        description: "single-token camelCase (e.g. threatDetection)"
        required: true
        type: string
      repoType:
        description: "engineering|operations|applications|governance|content" # retained until taxonomy review
        required: true
        type: string
      visibility:
        description: "public or private"
        required: true
        type: string
        default: private
      description:
        description: "Short description of purpose and scope"
        required: true
        type: string
      homepage:
        description: "Optional homepage URL"
        required: false
        type: string

permissions: {}

jobs:
  deprecated:
    runs-on: ubuntu-latest
    steps:
      - name: notice
        run: |
          echo "This workflow is deprecated. Use dispatch-repository-factory or generate-repository-service reusable workflow instead." && exit 1
