name: governance-guards

on:
  issues:
    types: [opened, edited]

permissions:
  contents: read
  issues: write

concurrency:
  group: governance-guards-${{ github.ref }}
  cancel-in-progress: true

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: enforceMinimumFields
        uses: actions/github-script@v7
        with:
          script: |
            const body = (context.payload.issue.body || '').toLowerCase();
            const required = [
              'pillar',
              'domain',
              'initiativeTitle',
              'purpose',
              'scope',
              'capabilityAreas',
              'deliverables',
              'successIndicators'
            ];
            const hasPillar = body.includes('pillar');
            const hasArchetype = body.includes('archetype');
            const missing = required.filter(k => {
              if (k === 'pillar') return !hasPillar && !hasArchetype;
              return !body.includes(k.toLowerCase());
            });
            if (missing.length) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: `❌ Missing fields: ${missing.join(', ')}`
              });
              core.setFailed('Missing required fields');
            }

      - name: enforceCamelCaseTitle
        uses: actions/github-script@v7
        with:
          script: |
            const title = context.payload.issue.title || '';
            const noPrefix = title.replace(/\[.*?\]\s*/, '');
            if (/[A-Z_]/.test(noPrefix)) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: '❌ Use camelCase in titles after the [Type] prefix'
              });
              core.setFailed('Title not in camelCase');
            }

      - name: validateOrganizationalStructure
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || '';
            const pillarMatch = body.match(/### pillar\s*\n\s*([^\n]+)/i);
            const archetypeMatch = body.match(/### archetype\s*\n\s*([^\n]+)/i);
            const domainMatch = body.match(/### domain\s*\n\s*([^\n]+)/i);
            const pillarValue = pillarMatch ? pillarMatch[1].trim() : (archetypeMatch ? archetypeMatch[1].trim() : null);
            
            if (!pillarValue || !domainMatch) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: '❌ Missing organisational structure metadata (pillar, domain)'
              });
              core.setFailed('Missing organisational metadata');
              return;
            }
            
            const pillar = pillarValue;
            const domain = domainMatch[1].trim();
            const validPillars = ['Protection', 'Sustenance', 'Innovation', 'Operations', 'Engagement', 'Growth', 'Guidance'];
            if (!validPillars.includes(pillar)) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: `❌ Invalid pillar: ${pillar}. Must be one of: ${validPillars.join(', ')}`
              });
              core.setFailed('Invalid pillar');
              return;
            }
            
            if (!/^[a-z][a-zA-Z]*$/.test(domain)) {
              await github.rest.issues.createComment({
                ...context.repo,
                issue_number: context.issue.number,
                body: `❌ Domain must be single-word camelCase starting with lowercase: ${domain}`
              });
              core.setFailed('Invalid domain format');
              return;
            }
            
            console.log(`✅ Organisational structure validated: ${pillar} → ${domain}`);

      - name: validateMcpContextCompliance
        if: contains(github.event.issue.body, 'contextManifest') || contains(github.event.issue.body, 'context') || contains(github.event.issue.body, 'anchor')
        uses: actions/github-script@v7
        with:
          script: |
            const body = context.payload.issue.body || '';
            const contextKeywords = ['contextManifest', 'context', 'anchor', 'redaction', 'spectra.'];
            const hasContextContent = contextKeywords.some(k => body.toLowerCase().includes(k.toLowerCase()));
            if (hasContextContent) {
              const privacyKeywords = ['redaction', 'privacy', 'logContent', 'defaultDeny'];
              const hasPrivacyConsiderations = privacyKeywords.some(k => body.toLowerCase().includes(k.toLowerCase()));
              if (!hasPrivacyConsiderations) {
                await github.rest.issues.createComment({
                  ...context.repo,
                  issue_number: context.issue.number,
                  body: '⚠️ Context Privacy: Ensure redaction/privacy policies. See contracts/context/redactionPolicy.json'
                });
              }
              const frameworkKeywords = ['framework', 'contract', 'schema', 'pinned', 'SHA'];
              const hasFrameworkCompliance = frameworkKeywords.some(k => body.toLowerCase().includes(k.toLowerCase()));
              if (!hasFrameworkCompliance) {
                await github.rest.issues.createComment({
                  ...context.repo,
                  issue_number: context.issue.number,
                  body: '📋 Framework is Law: Context changes must comply with contracts in contracts/context/.'
                });
              }
              console.log('✅ Context compliance validated');
            }
