name: labels-seeder

on:
  workflow_dispatch: {}

permissions:
  contents: read
  issues: write

concurrency:
  group: labels-seeder-${{ github.ref }}
  cancel-in-progress: true

jobs:
  seed:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: applyLabels
        uses: actions/github-script@v7
        with:
          script: |
            const path = `${process.cwd()}/.github/labels.json`;
            const labels = require(path);
            for (const l of labels) {
              try {
                await github.rest.issues.createLabel({
                  owner: context.repo.owner,
                  repo: context.repo.repo,
                  name: l.name, color: l.color, description: l.description
                });
              } catch (e) {
                if (e.status === 422) {
                  await github.rest.issues.updateLabel({
                    owner: context.repo.owner,
                    repo: context.repo.repo,
                    name: l.name, color: l.color, description: l.description
                  });
                } else {
                  throw e;
                }
              }
            }
