name: Organizational Structure Validator
description: "Validates repository metadata against SPECTRA canonical organizational structure"

on:
  workflow_call:
    inputs:
      dream:
        description: "Organizational dream/vision"
        required: true
        type: string
      archetype:
        description: "High-level capability archetype"
        required: true
        type: string
      domain:
        description: "Single-word camelCase domain"
        required: true
        type: string
      repository:
        description: "Repository name"
        required: false
        type: string
        default: ${{ github.repository }}

jobs:
  validate-org-structure:
    runs-on: ubuntu-latest
    name: Validate Organizational Structure
    
    steps:
      - name: Checkout .github repository for schema
        uses: actions/checkout@v4
        with:
          repository: SPECTRADataSolutions/.github
          path: .github-repo
          
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install dependencies
        run: |
          npm install -g ajv-cli
          
      - name: Extract repository name
        id: repo-name
        run: |
          if [ -n "${{ inputs.repository }}" ]; then
            REPO_NAME="${{ inputs.repository }}"
          else
            REPO_NAME="${{ github.repository }}"
          fi
          REPO_BASENAME=$(basename "$REPO_NAME")
          echo "repository=$REPO_BASENAME" >> $GITHUB_OUTPUT
          
      - name: Create metadata object for validation
        id: metadata
        run: |
          cat > metadata.json << EOF
          {
            "dream": "${{ inputs.dream }}",
            "archetype": "${{ inputs.archetype }}",
            "domain": "${{ inputs.domain }}",
            "repository": "${{ steps.repo-name.outputs.repository }}"
          }
          EOF
          echo "Created metadata object:"
          cat metadata.json
          
      - name: Validate against schema
        run: |
          echo "Validating organizational structure metadata..."
          ajv validate \
            -s .github-repo/contracts/orgStructureMetadata.json \
            -d metadata.json
            
      - name: Validate naming conventions
        run: |
          DREAM="${{ inputs.dream }}"
          ARCHETYPE="${{ inputs.archetype }}"
          DOMAIN="${{ inputs.domain }}"
          REPO="${{ steps.repo-name.outputs.repository }}"
          
          echo "Validating naming conventions..."
          
          # Check dream is SPECTRA
          if [ "$DREAM" != "SPECTRA" ]; then
            echo "❌ Dream must be 'SPECTRA', got: $DREAM"
            exit 1
          fi
          
          # Check archetype is in allowed list
          case $ARCHETYPE in
            "Guidance"|"Innovation"|"Engagement"|"Operations"|"Protection"|"Sustenance"|"Growth")
              echo "✅ Valid archetype: $ARCHETYPE"
              ;;
            *)
              echo "❌ Invalid archetype: $ARCHETYPE"
              echo "   Must be one of: Guidance, Innovation, Engagement, Operations, Protection, Sustenance, Growth"
              exit 1
              ;;
          esac
          
          # Check domain is single word and camelCase
          if [[ ! $DOMAIN =~ ^[a-z][a-zA-Z]*$ ]]; then
            echo "❌ Domain must be single-word camelCase (starting with lowercase): $DOMAIN"
            exit 1
          fi
          
          # Check repository follows GitHub conventions
          if [[ ! $REPO =~ ^[a-zA-Z0-9._-]+$ ]]; then
            echo "❌ Repository name contains invalid characters: $REPO"
            exit 1
          fi
          
          echo "✅ All naming conventions validated successfully"
          
      - name: Validation Summary
        run: |
          echo "🎯 Organizational Structure Validation Complete"
          echo "   Dream: ${{ inputs.dream }}"
          echo "   Archetype: ${{ inputs.archetype }}"
          echo "   Domain: ${{ inputs.domain }}"
          echo "   Repository: ${{ steps.repo-name.outputs.repository }}"
          echo "   ✅ All validations passed"