name: update-dependency-graph

on:
  issues:
    types: [opened, edited, labeled]

jobs:
  update:
    if: contains(github.event.issue.labels.*.name, 'type:dependency') || contains(github.event.issue.labels.*.name, 'type:decision')
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v4

      - name: updateGraph
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const path = 'dependency-graph/graph.json';
            const body = context.payload.issue.body || '';

            function grab(re) {
              const m = body.match(re);
              return m ? m[1].trim() : null;
            }

            const from = grab(/fromElement[\s\S]*?\n([\s\S]*?)\n/i);
            const to = grab(/toElement[\s\S]*?\n([\s\S]*?)\n/i);

            const g = JSON.parse(fs.readFileSync(path, 'utf8'));
            if (from && to) {
              if (!g.nodes.includes(from)) g.nodes.push(from);
              if (!g.nodes.includes(to)) g.nodes.push(to);
              g.edges.push({ from, to, at: new Date().toISOString() });
              fs.writeFileSync(path, JSON.stringify(g, null, 2));
            }

      - name: commitGraph
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore(dependencyGraph): update graph"
