name: verify-policy-attestation

on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "framework/policies/*policy.*"
      - "framework/policy-digests.txt"

permissions:
  contents: read

jobs:
  verify:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: verify-digests
        id: verify
        uses: ./.github/actions/verify-policy-digests
      - name: summary
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const mismatch='${{ steps.verify.outputs.mismatch }}'==='true';
            const stale='${{ steps.verify.outputs.stale }}'==='true';
            let lines=[];
            if(!mismatch && !stale){ lines.push('All policy digests verified and fresh.'); }
            if(mismatch) lines.push('Digest mismatch detected.');
            if(stale) lines.push('Attestation stale (re-run policy-attestation).');
            core.summary.addHeading('Policy Attestation Verification').addList(lines).write();
            if(mismatch || stale) core.setFailed('Policy attestation verification failed');
