# MCP Provider Configuration
# Defines connection and security settings for Model Context Protocol providers
# following default-deny security principles

metadata:
  version: 1.0.0
  environment: development
  lastUpdated: "2024-01-01T00:00:00Z"

security:
  defaultPolicy: deny
  authenticationRequired: true
  auditLogging: true
  secretRedaction: true

providers:
  data:
    enabled: false  # Enable only when needed
    endpoint: "https://data.example.com/mcp"
    authentication:
      type: token
      envVariable: DATA_TOKEN
    rateLimits:
      requestsPerMinute: 30
      requestsPerHour: 1000
    allowedOperations:
      - read
      - search
      - query

  git:
    enabled: false  # Enable only when needed
    endpoint: "https://api.github.com"
    authentication:
      type: token
      envVariable: GITHUB_TOKEN
    rateLimits:
      requestsPerMinute: 20
      requestsPerHour: 500
    allowedOperations:
      - read
      - search
      - list
    repositoryAllowlist:
      - SPECTRADataSolutions/public-repo
      # Add specific repositories as needed

  ticketing:
    enabled: false  # Enable only when needed
    endpoint: "https://ticketing.example.com/api"
    authentication:
      type: api-key
      envVariable: TICKETING_TOKEN
    rateLimits:
      requestsPerMinute: 10
      requestsPerHour: 200
    allowedOperations:
      - read
      - search
      - list
    projectAllowlist:
      - PROJ-001
      # Add specific project IDs as needed

monitoring:
  metricsEnabled: true
  healthChecks:
    enabled: true
    intervalSeconds: 60
  alerting:
    errorThreshold: 0.05  # 5% error rate
    latencyThreshold: 2000  # 2 seconds