name: languageStyleGuard

on:
  pull_request:
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - "**/*.txt"
  push:
    paths:
      - "**/*.md"
      - "**/*.mdx"
      - "**/*.txt"
  workflow_dispatch: {}

jobs:
  enforceLanguageStyle:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Run language style enforcement
        run: |
          python scripts/enforceLanguageStyle.py